// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package spring.projetodsc.domain;

import org.springframework.beans.factory.annotation.Configurable;
import spring.projetodsc.domain.ClienteIntegrationTest;

privileged aspect ClienteIntegrationTest_Roo_Configurable {
    
    declare @type: ClienteIntegrationTest: @Configurable;
    
}
